### ISSUE TITLE
Diagram error in Typora 0.9.98

### ISSUE THREAD

**Issue by Poweril** [gilbertohasnofb/typora-panda-theme#3]
Worked perfectly on previous version (0.9.96), but after updating Typora to 0.9.98 two of the diagram failed to show, since the color of the words is now matching the background. I am using on Windows 10.
Could this happens over and over with future updates? I wish I could edit the theme myself, but I would appreciate some help.
Thanks in advance!

# Error 1: mermaid sequence diagram
```mermaid
%% Example of sequence diagram
  sequenceDiagram
    Alice->>Bob: Hello Bob, how are you?
    alt is sick
    Bob->>Alice: Not so good :(
    else is well
    Bob->>Alice: Feeling fresh like a daisy
    end
    opt Extra response
    Bob->>Alice: Thanks for asking
    end
```
![image](https://user-images.githubusercontent.com/31843493/102209861-60230f80-3f0c-11eb-9f8d-7ec910e87afb.png)

# Error 2: mermaid flowchat
```mermaid
graph LR
A[Hard edge] -->B(Round edge)
    B --> C{Decision}
    C -->|One| D[Result one]
    C -->|Two| E[Result two]
```
![image](https://user-images.githubusercontent.com/31843493/102210177-cf006880-3f0c-11eb-9bc8-d6b84af030ac.png)

**Comment by gilbertohasnofb** [comment]
@Poweril Hi, thanks for the report. I will chase this with the developers of Typora, it seems that most themes are broken at the moment. It seems to me that while the background colour of nodes are changing according to the theme, the text colour is not, resulting in what you see above. As a temporary fix, replace `--node-fill: var(--bg-color5);` on line 102 with `--node-fill: #888 /* var(--bg-color5); */`, so that at least you can read your diagrams.

> Could this happens over and over with future updates?

This is beyond my control I'm afraid. But do report any issues here and I will try to fix them if this sort of thing happens in the future. Do keep in mind that Typora is still under development, so these sort of changes that break things are common.

**Comment by gilbertohasnofb** [comment]
This issue has been fixed in the new v1.3 release. Thanks for the report.

**Comment by Poweril** [comment]
Thanks for taking time to look into this!

**Comment by gilbertohasnofb** [comment]
No problems :smile:
